# Run the code like
int('') # code will be terminated here so that the next line is not executed.
1+1  


# try this
try:
    int('')
except Exception:
    print('Error!')
1+1
    
